### ISSUE TITLE
eye detection example

### ISSUE THREAD

**Issue by marcomoscardini** [mtschirs/js-objectdetect#1]
I am after a valid example of your objectdetect.js to detect eyes in a face ROI. I have succeeded to detect one eye and integrate into the image example. I would like to detect eyes within the face being detected, can it be done?

this will detect the face and one eye, what do I nee to do to make it detect 2 eyes in a face region, can I make it work with many faces at the same time?

on openCV C++ I did manage, but in JS I am having hard time, can u help?

<!DOCTYPE html>
<html lang="en">
<head>
    <script src="js/objectdetect.js"></script>
    <script src="js/objectdetect.frontalface.js"></script>
    <script src="js/objectdetect.eye.js"></script>  
    <script src="http://code.jquery.com/jquery-1.8.0.min.js"></script>
    <script src="js/jquery.objectdetect.js"></script>
    <script>
    $(window).load(function() {
        $("#face").objectdetect("all", {classifier: objectdetect.frontalface}, function(coords) {
            $("<div />", {
                "css": {
                    "border":   "2px solid #00FF00",
                    "position": "absolute",
                    "left":     ($("#face").offset().left + coords[0][0]) + "px",
                    "top":      ($("#face").offset().top  + coords[0][1]) + "px",
                    "width":    coords[0][2] + "px",
                    "height":   coords[0][3] + "px"
                }
            }).appendTo("body");

```
        $("#face").objectdetect("all", {classifier: objectdetect.eye}, function(coords) {
            $("<div />", {
                "css": {
                    "border":   "2px solid #F00",
                    "position": "absolute",
                    "left":     ($("#face").offset().left + coords[0][0]) + "px",
                    "top":      ($("#face").offset().top  + coords[0][1]) + "px",
                    "width":    coords[0][2] + "px",
                    "height":   coords[0][3] + "px"
                }
            }).appendTo("body");
        });

    });
});

</script>
```

</head>
<body>
    <img id="face" src="img/mona.jpg" width="300px">
</body>
</html>

**Comment by krsoninikhil** [comment]
> It can be done, but not yet with the jQuery plugin. I think that adding an option called "selection" that allows to restrict the search window might be the answer to your question.

Is there any such option of providing 'selection' in js (without jquery)?
Also I can't find any reference to the functions used in example, any links on that will be very helpful.
