### ISSUE TITLE
not working after custom style change

### ISSUE THREAD

**Issue by mourdeveloper** [mtschirs/js-objectdetect#18]
i did below changes to video

<video id="video" style="float: left; margin-right: 1em;border:1px dotted red;height:800px"></video>

after that sunglasses show at wrong position why so have i to make changes at other place also ??

**Comment by mtschirs** [comment]
Hi, you have to adapt the relative positions. Alternatively, you could combine sunglasses or any other overlay and the camera image directly on the HTML5 canvas.
