### ISSUE TITLE
Face detection with Pre-recorded video stream

### ISSUE THREAD

**Issue by Muhammad-Ikram-Ul-Haq** [mtschirs/js-objectdetect#20]
Hi! 
We have an web application and there we are currently using Headtrackr.js library for face detection. We want to do face detection with pre-recorded video stream. Headtrackr library provides us such feature to either use webcam for real time face detection or pre-recorded video stream. Now we just want to use js-objectdetect library and trying to integrate it with pre-recorded video stream. Is that possible through this library to either use webcam for real time face detection or with pre-recorded video stream? We will really appreciate your consideration for this issue .

Thanks

**Comment by mtschirs** [comment]
Yes, it is possible. The video source doesn't matter, detection can be performed on any HTML video or image element no matter where the video or image data comes from.
