### ISSUE TITLE
noise detections > real detections

### ISSUE THREAD

**Issue by jonatas** [mtschirs/js-objectdetect#25]
Hi, I'm trying to use fist and open hand classifiers. I'm getting a lot of non-sense finds. I start changing the scaleFactor parameter from 0.1 to 2 and I didn't get so much success finding a best scale factor. Some times it works fine but I got a lot of non sense findings.

I started using video stream directly. With much noise, I tried to migrate to find on a gray image instead.

I got crazy with so much signals with no connection with real hands.

I put  red for fist hands and kind of orange for open hands. The face is recognized by jsfeat classifiers and it uses a green square do identify the face. The same method I used to plot face, I plot for hands.

![detect-multiple-hands-fail](https://cloud.githubusercontent.com/assets/15484/9578140/f60c14ae-4fbd-11e5-883a-d278468a9a67.png)

I don't understand how much sensibility of camera or even the not blank background can break the things here. I got some nice finds too. But so much noise was find as hands. Have some one deal with something like that?

**Comment by mtschirs** [comment]
There is some useful general information about the parameters used by js-objectdetect in https://github.com/mtschirs/js-objectdetect/issues/22

The scaleFactor must always be > 1, a value of 1.05 or 1.1 is plausible. A small scaleFactor results in a better detection performance, but makes the detection process slower.

You don't need to convert your video stream or image to grayscale. The conversion is automatically done by detector.detect().

"The face is recognized by jsfeat classifiers" - object detection in jsfeat is based on an older version of js-objectdetect. The classifiers might be incompatible. 

Did you try out the official examples? They should have a good detection performance.

**Comment by boynet** [comment]
from my experience you need to check the confidence of the result.
I did it by console.log the confidence in every match and play with it while the console is open.

to solve false positive:
check the value when you get falst positive and when positive, and make some smart guess threshold.

for better positive experience you need a few things start  with getting the averge fps, than make some smart guess(again) of detection temporary losing of object.

so the problem with the fist demo is when you scroll down and the fist  lost for 1 frame the whole scroll is stopped instead of keep going for a few frames while trying to redetect the fist, this will give you a lot more "smooth" detections.

for example: if on pc you get 60 fps it may be ok to lose the object for 5-15 frames until "officaly" declare a state of "fist not found" (the user will not notice it as it just a few ms)

the same for reverse scenario if you dont have a detection for some time and suddenly there is a detection dont automatically accept it, wait a few frames to see if it consist only than "accept" the detection

**Comment by jonatas** [comment]
@mtschirs thank you for the feedback, and the issue #22 has a lot of things I'll try. I really didn't knew that jsfeat was based on js-objectdetect. Really cool!

I'm still using some math functions from jsfeat like `jsfeat.matrix_t`, `gaussian_blur`, `compute_integral_image`,`group_rectangles`. Did you reimplement some of these functions that I can use from js-objectdetect here?

**Comment by mtschirs** [comment]
Have a look at the sourcecode and you will find functions to perform a blur, to compute integral images and group rectangles. However, I don't know what matrix_t does or represents; there is probably no equivalent in js-objectdetect.

Only the object detection part of js-feat is based on js-objectdetect (an incompatible older version).

**Comment by jonatas** [comment]
@boynet thanks for your feedback. I really try to inspect the confidence. But `detect` function returns only the final squares. How can I fetch the confidence of each detection?

**Comment by jonatas** [comment]
@mtschirs thank you! I'll try to use these functions! Matrix_t is a kind of matrix can be transformed easily by other jsfeat functions.

**Comment by mtschirs** [comment]
@jonatas detector.detect returns arrays with 5 indices; the first 4 are the x,y,width,height of the rectangle and the 5th is the confidence (number of grouped rectangles). 
You can turn-off grouping of rectangles and re-run detection for e.g. debugging purposes via detector.detect(image, false, ...)

**Comment by jonatas** [comment]
Thank you @mtschirs. I really need to deep reading the code before post my foo questions! Thank you for your time!

**Comment by jonatas** [comment]
I got a really cool effect inspecting using the square alpha channel over the confidence of results.

![detect confidence as opacity](https://cloud.githubusercontent.com/assets/15484/9607228/63fc96ce-509e-11e5-8e96-5f8230c6d471.gif)

**Comment by jonatas** [comment]
Hey @mtschirs, we migrate our face detection from jsfeat! We got 10 times faster :dancers:

**Comment by mtschirs** [comment]
Than you @jonatas for all your feedback! I appreciate that. Feel free to share your experiments / results / issues with js-objectdetect in the future too, if you like; we all can only benefit from it :+1:

**Comment by jonatas** [comment]
Cool! I'll try to prepare some samples!

On Wed, Sep 16, 2015 at 11:38 AM, mtschirs notifications@github.com wrote:

> Than you @jonatas https://github.com/jonatas for all your feedback! I
> appreciate that. Feel free to share your experiments / results / issues
> with js-objectdetect in the future too, if you like; we all can only
> benefit from it [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mtschirs/js-objectdetect/issues/25#issuecomment-140761493
> .

## 

atenciosamente,

Jônatas Davi Paganini.

## 

[ _ideia.me http://ideia.me *_eu\* _invent.to http://invent.to/_ ]
46 9911 7879
