### ISSUE TITLE
Convert OPEN cv xml classifiers to your js format file

### ISSUE THREAD

**Issue by ludovicpages** [mtschirs/js-objectdetect#7]
Hi. 
Can you tell us the way you converted the xml classifiers from OPEN CV to your js fle format ? I tried the HAAR.js converter, but the generated js file is different from yours.
I actually need the nose classifiers.

Thanks ;)

**Comment by mtschirs** [comment]
Here is a custom script to convert the new OpenCV xml format haarcascades produced by `opencv_traincascade`: https://gist.github.com/mtschirs/df8d8dc5ff56cc7187b1

**Comment by HoracioEspinosa** [comment]
how i can convert my haarcascade in opencv 2.4 version with a similar python code? :( thanks
